# Generated by Django 6.0.4 on 2026-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurantstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
