# Generated by Django 6.0.4 on 2026-04-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
