# Generated by Django 6.0.4 on 2026-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
