# Generated by Django 6.0.4 on 2026-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
