# Generated by Django 6.0.4 on 2026-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='excess_order_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_excess_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_acceptance_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
