# Generated by Django 6.0.4 on 2026-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_excess_order_expiry_order_is_excess_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
